// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(BDZawodnicy))]
    partial class BDZawodnicyModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Plywak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyAktywnyZawodnik")
                        .HasColumnType("bit");

                    b.Property<byte?>("IloscZlotychMedali")
                        .HasColumnType("TINYINT");

                    b.Property<string>("ImieNazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("NajlepszyCzas")
                        .HasColumnType("NUMERIC(5,2)");

                    b.Property<decimal>("RokUrodzenia")
                        .HasColumnType("NUMERIC(4,0)");

                    b.HasKey("Id");

                    b.ToTable("Plywacy");
                });
#pragma warning restore 612, 618
        }
    }
}
